scifight/urls.py
from django.conf.urls import include, url
from scifight import views


tournament_urls = [
    url(r'^$',                                           views.tournament,   name='tournament'),
    url(r'^schedule/$',                                  views.schedule,     name='schedule'),
    url(r'^fight/(?P<fight_id>[0-9]+)/$',                views.fight,        name='fight'),
    url(r'^rooms/$',                                     views.rooms,        name='rooms'),
    url(r'^room/(?P<room_id>[0-9]+)/$',                  views.room,         name='room'),
    url(r'^teams/$',                                     views.teams,        name='teams'),
    url(r'^team/(?P<team_id>[0-9]+)/$',                  views.team,         name='team_id'),
    url(r'^team/(?P<team_slug>[\w_-]+)/$',               views.team,         name='team_slug'),
    url(r'^participants/$',                              views.participants, name='participants'),
    url(r'^participant/(?P<participant_id>[0-9]+)/$',    views.participant,  name='participant'),
    url(r'^leaders/$',                                   views.leaders,      name='leaders'),
    url(r'^leader/(?P<leader_id>[0-9]+)/$',              views.leader,       name='leader'),
    url(r'^jury/$',                                      views.jury,         name='jury'),
    url(r'^juror/(?P<jury_id>[0-9]+)/$',                 views.juror,        name='juror'),
    url(r'^problems/$',                                  views.problems,     name='problems'),
    url(r'^problem/(?P<problem_num>[0-9]+)/$',           views.problem,      name='problem'),
]

urlpatterns = [
    url(r'^(?P<tournament_slug>[\w_-]+)/',               include(tournament_urls, namespace='scifight')),
]

scifight_proj/urls.py
from scifight import urls
from django.conf.urls import url, include
from django.contrib import admin
from scifight.views import index

urlpatterns = [
    url(r'^$',      index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^',       include(urls,)),
]

scifight/models.py
from django.db   import models
from django.core import exceptions
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.translation   import ugettext as _tr

SLUG_LENGTH = 20
""" Maximum length of slug fields. This value must be large enough to hold
    a URL path component of reasonable length. No one is going to remember
    and read overly long addresses."""

NAME_LENGTH = 140
""" Maximum length of name fields in various models. This value should be
    long enough to hold any reasonable personal name, university name, district
    name, or other things like these. """

TEXT_LENGTH = 1024
""" Maximum length of descriptions fields in models below. This value should be
    long enough to hold an average paragraph of descriptive text. Maybe,
    a thousand or two of characters. """

GRADE_LENGTH = 20
""" Maximum length of the `grade` field. This value should be long enough to
    hold a number plus possible brief one-word explanation. """


class TeamIdentity(models.Model):

    def __str__(self):
        # For people to be able to guess where *exactly* they may have seen
        # this team before, show it's latest known name and tournament it
        # participated in.
        latest_team = self.teams.order_by("-tournament__opening_date").first()
        if latest_team:
            return _tr("TID#{0}: «{1}» on {2}").format(self.pk,
                                             latest_team.name,
                                             latest_team.tournament.short_name)
        else:
            return _tr("TID#{0}").format(self.pk)


class PersonIdentity(models.Model):

    def __str__(self):

        # Shorthand function. Will return 'None' if nothing is found.
        def get_most_recent(objs: models.manager.Manager):
            return objs.order_by("-tournament__opening_date").first()

        latest_juror       = get_most_recent(self.jury)
        latest_leader      = get_most_recent(self.leaders)
        latest_participant = get_most_recent(self.participants)

        avatars = {latest_juror, latest_leader, latest_participant}
        avatars.remove(None)

        if not avatars:
            return _tr("HID#{0}").format(self.pk)

        latest_avatar = max(avatars, key=lambda a: a.tournament.closing_date)
        return _tr("HID#{0}: {1} on {2}").format(self.pk,
                                        latest_avatar.short_name,
                                        latest_avatar.tournament.short_name)


class TeamOrigin(models.Model):
    place_name    = models.CharField(max_length=NAME_LENGTH)

    def __str__(self):
        return self.place_name

    class Meta:
        verbose_name        = _tr("Team origin")
        verbose_name_plural = _tr("Team origins")

    class Meta:
        ordering = ['place_name']


class PersonOrigin(models.Model):
    place_name    = models.CharField(max_length=NAME_LENGTH)

    def __str__(self):
        return self.place_name

    class Meta:
        ordering  = ['place_name']


class Tournament(models.Model):
    full_name     = models.CharField(max_length=NAME_LENGTH, unique=True)
    short_name    = models.CharField(max_length=NAME_LENGTH, unique=True)
    slug          = models.SlugField(max_length=SLUG_LENGTH, unique=True)
    description   = models.TextField(blank=True)
    opening_date  = models.DateField()
    closing_date  = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.short_name

    class Meta:
        ordering  = ['opening_date']


class Team(models.Model):
    tournament    = models.ForeignKey(Tournament)
    identity      = models.ForeignKey(TeamIdentity, related_name="teams",
                                      null=True, blank=True)
    name          = models.CharField(max_length=NAME_LENGTH)
    slug          = models.SlugField(max_length=SLUG_LENGTH,
                                     null=True, blank=True)
    description   = models.TextField(max_length=TEXT_LENGTH, blank=True)
    origin        = models.ForeignKey(TeamOrigin, null=True, blank=True)

    def clean(self):
        super().clean()

        # Force Django to always store SQL NULL for slug instead of an empty
        # string, thus making 'unique_together' work again.
        # NOTE: in SQL NULLs are treated as unique values.
        if self.slug == "":
            self.slug = None

    def save(self, *args, **kwargs):
        if self.identity is None:
            new_identity = TeamIdentity()
            new_identity.save()

            self.identity = new_identity

        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        ordering        = ['tournament', 'name']
        unique_together = ('tournament', 'slug')


class Participant(models.Model):
    tournament    = models.ForeignKey(Tournament)
    identity      = models.ForeignKey(PersonIdentity,
                                      related_name="participants",
                                      null=True, blank=True)
    full_name     = models.CharField(max_length=NAME_LENGTH)
    short_name    = models.CharField(max_length=NAME_LENGTH)
    origin        = models.ForeignKey(PersonOrigin, null=True, blank=True)
    grade         = models.CharField(max_length=GRADE_LENGTH, blank=True)
    team          = models.ForeignKey(Team)
    is_captain    = models.BooleanField()

    def fill_tournament(self):
        self.tournament = self.team.tournament

    def save(self, *args, **kwargs):
        if self.identity is None:
            new_identity = PersonIdentity()
            new_identity.save()

            self.identity = new_identity

        super().save(*args, **kwargs)

    def __str__(self):
        return self.short_name

    class Meta:
        ordering        = ['tournament', 'full_name']
        unique_together = ('tournament', 'identity')


class Leader(models.Model):
    tournament    = models.ForeignKey(Tournament)
    identity      = models.ForeignKey(PersonIdentity, related_name="leaders",
                                      null=True, blank=True)
    full_name     = models.CharField(max_length=NAME_LENGTH)
    short_name    = models.CharField(max_length=NAME_LENGTH)
    origin        = models.ForeignKey(PersonOrigin, null=True, blank=True)
    team          = models.ForeignKey(Team)

    def fill_tournament(self):
        self.tournament = self.team.tournament

    def save(self, *args, **kwargs):
        if self.identity is None:
            new_identity = PersonIdentity()
            new_identity.save()

            self.identity = new_identity

        super().save(*args, **kwargs)

    def __str__(self):
        return self.short_name

    class Meta:
        ordering        = ['tournament', 'full_name']
        unique_together = ('tournament', 'identity')


class Juror(models.Model):
    tournament    = models.ForeignKey(Tournament)
    identity      = models.ForeignKey(PersonIdentity, related_name="jury",
                                      null=True, blank=True)
    full_name     = models.CharField(max_length=NAME_LENGTH)
    short_name    = models.CharField(max_length=NAME_LENGTH)
    origin        = models.ForeignKey(PersonOrigin, null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.identity is None:
            new_identity = PersonIdentity()
            new_identity.save()

            self.identity = new_identity

        super().save(*args, **kwargs)

    def __str__(self):
        return self.short_name

    class Meta:
        ordering        = ['tournament', 'full_name']
        unique_together = ('tournament', 'identity')


class Room(models.Model):
    tournament    = models.ForeignKey(Tournament)
    designation   = models.CharField(max_length=NAME_LENGTH)
    sorting_key   = models.FloatField(null=True, blank=True)
    slug          = models.SlugField(max_length=SLUG_LENGTH)

    def __str__(self):
        return self.designation

    class Meta:
        ordering        = ['sorting_key']
        unique_together = ('tournament', 'slug')


class Problem(models.Model):
    tournament    = models.ForeignKey(Tournament)
    problem_num   = models.IntegerField(db_index=True)
    title         = models.CharField(max_length=NAME_LENGTH)
    description   = models.TextField(max_length=TEXT_LENGTH, blank=True)

    def __str__(self):
        return _tr("#{0}. {1}").format(self.problem_num, self.title)

    class Meta:
        ordering        = ['tournament', 'problem_num']
        unique_together = ('tournament', 'problem_num')


class TournamentRound(models.Model):
    tournament    = models.ForeignKey(Tournament)
    round_num     = models.SmallIntegerField()
    opening_time  = models.DateTimeField()
    closing_time  = models.DateTimeField()

    def __str__(self):
        return str(self.round_num)

    class Meta:
        ordering        = ['round_num']
        unique_together = ('tournament', 'round_num')


class Fight(models.Model):

    # Python lacks proper enums and constants, so use these static
    # variables to refer to 'status' values from Python code.
    NOT_STARTED = 0
    IN_PROGRESS = 1
    COMPLETED   = 2

    _STATUS_CHOICES = [
        (NOT_STARTED, _tr("Not started")),
        (IN_PROGRESS, _tr("In progress")),
        (COMPLETED,   _tr("Completed"))]

    tournament    = models.ForeignKey(Tournament)
    round         = models.ForeignKey(TournamentRound)
    room          = models.ForeignKey(Room)
    start_time    = models.DateTimeField(null=True, blank=True)
    stop_time     = models.DateTimeField(null=True, blank=True)
    status        = models.PositiveSmallIntegerField(choices=_STATUS_CHOICES,
                                                     default=NOT_STARTED)
    team1         = models.ForeignKey(Team, related_name="+")
    team2         = models.ForeignKey(Team, related_name="+")
    team3         = models.ForeignKey(Team, related_name="+",

scifight/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from scifight import models

get_or_404 = get_object_or_404


def render_with_context(request, template, **context):
    return render(request, template, context)


def index(request):
    return render_with_context(request, 'scifight/index.html',
        tournaments = models.Tournament.objects.all(),
        title       = "Willcommen")


def tournament(request, tournament_slug):
    return render_with_context(request, 'scifight/tournament.html',
        tournament = get_or_404(models.Tournament, slug=tournament_slug))


def schedule(request, tournament_slug):
    tnmt = get_or_404(models.Tournament, slug=tournament_slug)
    return render_with_context(request, 'scifight/schedule.html',
        tournament      = tnmt,
        fights          = models.Fight.objects.filter(tournament=tnmt),
        nav_active_item = "schedule")


def fight(request, tournament_slug, fight_id):
    tnmt = get_or_404(models.Tournament, slug=tournament_slug)
    return render_with_context(request, 'scifight/fight.html',
        tournament      = tnmt,
        fight           = get_or_404(models.Fight, pk=fight_id, tournament=tnmt),
        nav_active_item = "schedule")


def rooms(request, tournament_slug):
    tnmt = get_or_404(models.Tournament, slug=tournament_slug)
    return render_with_context(request, 'scifight/rooms.html',
        tournament      = tnmt,
        rooms           = models.Room.objects.filter(tournament=tnmt),
        nav_active_item = "rooms")


def room(request, tournament_slug, room_id):
    tnmt = get_or_404(models.Tournament, slug=tournament_slug)
    return render_with_context(request, 'scifight/room.html',
        tournament      = tnmt,
        room            = get_or_404(models.Room, pk=room_id, tournament=tnmt),
        nav_active_item = "rooms")


def teams(request, tournament_slug):
    tnmt = get_or_404(models.Tournament, slug=tournament_slug)
    return render_with_context(request, 'scifight/teams.html',
        tournament      = tnmt,
        teams           = models.Team.objects.filter(tournament=tnmt),
        nav_active_item = "teams")


def team(request, tournament_slug, team_id=None, team_slug=None):
    tnmt = get_or_404(models.Tournament, slug=tournament_slug)

    if team_id:
        team = get_or_404(models.Team, pk=team_id, tournament=tnmt)
    elif team_slug:
        team = get_or_404(models.Team, slug=team_slug, tournament=tnmt)
    else:
        raise Http404()

    return render_with_context(request, 'scifight/team.html',
        tournament      = tnmt,
        team            = team,
        nav_active_item = "teams")


def participants(request, tournament_slug):
    tnmt = get_or_404(models.Tournament, slug=tournament_slug)
    return render_with_context(request, 'scifight/participants.html',
        tournament      = tnmt,
        participants    = models.Participant.objects.filter(tournament=tnmt),
        nav_active_item = "participant")


def participant(request, tournament_slug, participant_id):
    tnmt = get_or_404(models.Tournament, slug=tournament_slug)
    return render_with_context(request, 'scifight/participant.html',
        tournament      = tnmt,
        participant     = get_or_404(models.Participant,
                                     pk=participant_id, tournament=tnmt),
        nav_active_item = "participants")


def leaders(request, tournament_slug):
    tnmt = get_or_404(models.Tournament, slug=tournament_slug)
    return render_with_context(request, 'scifight/leaders.html',
        tournament      = tnmt,
        leaders         = tnmt.leader_set.all(),
        nav_active_item = "leaders")


def leader(request, tournament_slug, leader_id):
    tnmt   = get_or_404(models.Tournament, slug=tournament_slug)
    leader = get_or_404(models.Leader, pk=leader_id, tournament=tnmt)
    return render_with_context(request, 'scifight/leader.html',
        tournament      = tnmt,
        leader          = leader,
        nav_active_item = "leaders")


def jury(request, tournament_slug):
    tnmt = get_or_404(models.Tournament, slug=tournament_slug)
    return render_with_context(request, 'scifight/jury.html',
        tournament      = tnmt,
        jury            = models.Juror.objects.filter(tournament=tnmt),
        nav_active_item = "jury")


def juror(request, tournament_slug, jury_id):
    tnmt  = get_or_404(models.Tournament, slug=tournament_slug)
    juror = get_or_404(models.Juror, pk=jury_id, tournament=tnmt)
    return render_with_context(request, 'scifight/juror.html',
        tournament      = tnmt,
        juror           = juror,
        nav_active_item = "jury")


def problems(request, tournament_slug):
    tnmt     = get_or_404(models.Tournament, slug=tournament_slug)
    problems = models.Problem.objects.filter(tournament=tnmt)
    return render_with_context(request, 'scifight/problems.html',
        tournament      = tnmt,
        problems        = problems,
        nav_active_item = "problems")


def problem(request, tournament_slug, problem_num):
    tnmt    = get_or_404(models.Tournament, slug=tournament_slug)
    problem = get_or_404(models.Problem,
                         problem_num=problem_num, tournament=tnmt)
    return render_with_context(request, 'scifight/problem.html',
        tournament      = tnmt,
        problem         = problem,
        nav_active_item = "problem")

scifight/templates/scifight/_base.html
{% load i18n %}
{% load staticfiles %}
{% load scifight_url %}

<!DOCTYPE html>
<html lang="{{ site.language }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head
         content must come *after* these tags. -->

    {% block title %}
        <title>{{ site.short_name }} </title>
    {% endblock %}

    <link href="{% static 'scifight/css/bootstrap.min.css' %}"
          rel="stylesheet">
    <link href="{% static 'scifight/css/navbar-static-top.css' %}"
          rel="stylesheet">
    <!-- <link href="{% static 'scifight/css/sticky-footer-navbar.css' %}"
          rel="stylesheet"> -->
</head>

<body>

{% block content %}
{% endblock %}

<footer class="footer">
    <div class="container">
        {% block footer %}
        {% endblock %}
    </div>
</footer>

<!-- JavaScript placed at the end of the document so the pages load faster -->
<script src="{% static 'scifight/js/jquery.min.js' %}"></script>
<script src="{% static 'scifight/js/bootstrap.min.js' %}"></script>

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static 'scifight/js/ie10-viewport-bug-workaround.js' %}"/>
</body>
</html>

scifight/templates/scifight/_inside_tournament.html
{% extends "scifight/_base.html" %}
{% load i18n %}
{% load scifight_url %}

{% block content %}
    {#  #}
    {% url "scifight:schedule"     tournament.slug as schedule_url %}
    {% url "scifight:rooms"        tournament.slug as rooms_url %}
    {% url "scifight:teams"        tournament.slug as teams_url %}
    {% url "scifight:participants" tournament.slug as participants_url %}
    {% url "scifight:leaders"      tournament.slug as leaders_url %}
    {% url "scifight:jury"         tournament.slug as jury_url %}
    {% url "scifight:problems"     tournament.slug as problems_url %}

    <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button"
                    class="navbar-toggle collapsed"
                    data-toggle="collapse"
                    data-target="#navbar"
                    aria-expanded="false"
                    aria-controls="navbar">
                <span class="sr-only">{% trans "Toggle navigation" %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
          <a class="navbar-brand"
             href="{{ tournament | scifight_url }}">{{ tournament.short_name }}
          </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                {% block navitems %}
                {% with nav_active_item as nai %}
                    <li {% if nai == "schedule" %} class="active" {% endif %}>
                        <a href="{{ schedule_url }}">
                        {% trans "Schedule" %}</a></li>
                    <li {% if nai == "rooms" %} class="active" {% endif %}>
                        <a href="{{ rooms_url }}">
                        {% trans "Rooms" %}</a></li>
                    <li {% if nai == "teams" %} class="active" {% endif %}>
                        <a href="{{ teams_url }}">
                        {% trans "Teams" %}</a></li>
                    <li {% if nai == "participants" %} class="active" {% endif %}>
                        <a href="{{ participants_url }}">
                        {% trans "Participants" %}</a></li>
                    <li {% if nai == "leaders" %} class="active" {% endif %}>
                        <a href="{{ leaders_url }}">
                        {% trans "Leaders" %}</a></li>
                    <li {% if nai == "jury" %} class="active" {% endif %}>
                        <a href="{{ jury_url }}">{% trans "Jury" %}</a></li>
                    <li {% if nai == "problems" %} class="active" {% endif %}>
                        <a href="{{ problems_url }}">
                        {% trans "Problems" %}</a></li>
                {% endwith %}
                {% endblock %}
            </ul>
        </div>
      </div>
    </nav>

    <div class="container">
        {%  block container_content %}
        {% endblock %}
    </div>

{% endblock %}

scifight/templates/scifight/fight.html
{% extends 'scifight/_inside_tournament.html' %}
{% load scifight_url %}

{% block container_content %}
    <p>Fight #{{ fight.fight_num }}</p>
    <p>Room:
        <a href="{{ fight.room | scifight_url }}">{{ fight.room.name }}</a>
    </p>
    <p>Start time: {{ fight.start_time }}</p>
    <p>Stop time: {{ fight.stop_time }}</p>
    <p>Status: {{ fight.status }}</p>

    <p>Team 1:
        <a href="{{ fight.team1 | scifight_url }}">{{ fight.team1.name }}</a>
    </p>
    <p>Team 2:
        <a href="{{ fight.team2 | scifight_url }}">{{ fight.team2.name }}</a>
    </p>
    {% if fight.team3 %}
        <p>Team 3:
            <a href="{{ fight.team3 | scifight_url }}">{{ fight.team3.name }}</a>
        </p>
    {% endif %}
    {% if fight.team4 %}
        <p>Team 4:
            <a href="{{ fight.team4 | scifight_url }}">{{ fight.team4.name }}</a>
        </p>
    {% endif %}
    <p>Jury:</p>
    <ul>
    {% for juror in jury %}
        <li><a href="{{ juror | scifight_url }}">{{ juror.full_name }}</a></li>
    {% endfor %}
    </ul>
    <hr>
    <h4>Actions:</h4>
    <hr>
    <ul>
        {% for fightstage in fightstages %}
            <p>#{{ fightstage.action_num }}</p>
            <p><a href="{{ fightstage.problem | scifight_url }}">
                Problem: {{ fightstage.problem.name }}</a></p>
            <p><a href="{{ fightstage.reporter | scifight_url }}">
                Reporter: {{ fightstage.reporter.short_name }}</a></p>
            <p><a href="{{ fightstage.opponent | scifight_url }}">
                Oppenent: {{ fightstage.opponent.short_name }}</a></p>
            <p><a href="{{ fightstage.reviewer | scifight_url }}">
                Reviewer: {{ fightstage.reviewer.short_name }}</a></p>
        {% endfor %}
    </ul>
{% endblock %}

scifight/templates/scifight/index.html
{% extends 'scifight/_base.html' %}
{% load scifight_url %}

{% block content %}
    <ul>
        {% for tournament in tournaments %}
            <li><a href="{{ tournament | scifight_url }}">
                    {{ tournament.full_name }} {{ tournament.opening_date }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

scifight/templates/scifight/juror.html
{% extends 'scifight/_inside_tournament.html' %}
{% load scifight_url %}

{% block container_content %}
    <h1>{{ juror.full_name }} ({{ juror.short_name}})</h1>
    <p>{{ juror.origin }}</p>
{% endblock %}

scifight/templates/scifight/leader.html
{% extends 'scifight/_inside_tournament.html' %}
{% load scifight_url %}

{% block container_content %}
    <p>{{ leader.full_name }}, ({{ leader.short_name }})</p>
    <p><a href="{{ leader.team | scifight_url }}">Team: {{ leader.team.name }}</a></p>
    <p>{{ leader.origin }}</p>
{% endblock %}

scifight/templates/scifight/leaders.html
{% extends 'scifight/_inside_tournament.html' %}
{% load scifight_url %}

{% block container_content %}
    {% for leader in leaders %}
        <p><a href="{{ leader | scifight_url }}">{{ leader.full_name }} ({{ leader.short_name }})</a></p>
        <p><a href="{{ leader.team | scifight_url }}">Team: {{ leader.team }}</a></p>
        <hr/>
    {% endfor %}
{% endblock %}

scifight/templates/scifight/participants.html
{% extends 'scifight/_inside_tournament.html' %}
{% load scifight_url %}

{% block container_content %}
    {% for participant in participants %}
        <p>
            <a href="{{ participant | scifight_url }}">
                {% if participant.full_name %}{{ participant.full_name }}
                {% else %} {{ participant.short_name }}
                {% endif %}
            </a>
        </p>
        <hr/>
    {% endfor %}
{% endblock %}

scifight/templates/scifight/room.html
{% extends 'scifight/_inside_tournament.html' %}
{% load scifight_url %}

{% block container_content %}
    <h1>{{ room.name }} room</h1>
    <ul>
        {% for fight in fights %}
            <li><a href="{{ fight | scifight_url }}">Fight #{{ fight.fight_num }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

scifight/templates/scifight/rooms.html
{% extends 'scifight/_inside_tournament.html' %}
{% load scifight_url %}

{% block container_content %}
    {% for room in rooms %}
        <p><a href="{{ room | scifight_url }}">room - {{ room.name }}</a></p>
        <hr/>
    {% endfor %}
{% endblock %}

scifight/templates/scifight/schedule.html
{% extends 'scifight/_inside_tournament.html' %}
{% load scifight_url %}

{% block container_content %}
    {% for fight in fights %}
        <p><a href="{{ fight | scifight_url }}">Fight#{{ fight.fight_num }}</a></p>
        <a href="{{ fight.room | scifight_url }}"><p>room {{ fight.room }}</p><a
        <p>start time {{ fight.start_time }}</p>
        <p>status {{ fight.status }}</p>
        <hr/>
    {% endfor %}
{% endblock %}

scifight/templates/scifight/team.html
{% extends 'scifight/_inside_tournament.html' %}
{% load scifight_url %}

{% block container_content %}
    <h1>{{ team.name }} team</h1>
    <p>{{ team.description }}</p>
    <p>{{ team.origin }}</p>
    <p>Liders:</p>
    {% for leader in leaders %}
        <p>{{ leader.full_name }}</p>
    {% endfor %}
    <ul>
        {% for participant in participants %}
            <li>
                <a href="{{ participant | scifight_url }}">
                    {% if participant.full_name %}{{ participant.full_name }}
                    {% else %} {{ participant.short_name }}
                    {% endif %}
                </a>
                {% if participant.is_captain %}
                    <- captain
                {% endif %}
            </li>
        {% endfor %}
    </ul>
{% endblock %}

scifight/templates/scifight/teams.html
{% extends 'scifight/_inside_tournament.html' %}
{% load scifight_url %}

{% block container_content %}
    {% for team in teams %}
        <p><a href="{{ team | scifight_url }}">Team - {{ team.name }}</a></p>
        <hr/>
    {% endfor %}
{% endblock %}

scifight/templates/scifight/tournament.html
{% extends 'scifight/_inside_tournament.html' %}

{% block container_content %}
    <h1>{{ tournament.full_name }}</h1>
    <p>{{ tournament.description }}</p>
    <p>{{ tournament.opening_date }}</p>

    <ul>
        <li><a href="{% url 'scifight:schedule' tournament.slug %}"><p>Shedule</p></a></li>
        <li><a href="{% url 'scifight:rooms' tournament.slug %}"><p>Rooms</p></a></li>
        <li><a href="{% url 'scifight:teams' tournament.slug %}"><p>Teams</p></a></li>
        <li><a href="{% url 'scifight:participants' tournament.slug %}"><p>Particapants</p></a></li>
        <li><a href="{% url 'scifight:leaders' tournament.slug %}"><p>Leaders</p></a></li>
        <li><a href="{% url 'scifight:jury' tournament.slug %}"><p>Jury</p></a></li>
        <li><a href="{% url 'scifight:problems' tournament.slug %}"><p>Problems</p></a></li>
    </ul>
{% endblock %}